# Uncomment the next line to define a global platform for your project
  platform :ios, '11.1'

target 'Koala' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Koala
  pod 'Sipp3XII', :path => '~/desktop/sipp-pods-master'

end
